openapi: 3.1.1
info:
  title: rustNPS API v1
  version: 0.1.0
  license:
    name: MIT
    identifier: MIT
  description: API v1 specification for the rustNPS application.
  contact:
    name: Unartig Team

servers:
  - url: /v1
    description: local
